# Generated by Django 3.0.4 on 2020-03-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AC_certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_autoassinado', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Certificados_emitidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado', models.BinaryField()),
            ],
        ),
    ]
