# Generated by Django 3.0.4 on 2020-03-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_ac_certificado_certificados_emitidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac_certificado',
            name='chave_privada',
            field=models.BinaryField(default=b'ab'),
        ),
    ]
