# Generated by Django 3.0.4 on 2020-03-13 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_ac_certificado_chave_privada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ac_certificado',
            name='chave_privada',
        ),
    ]
