# Generated by Django 3.0.4 on 2020-03-13 13:12

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_ac_certificado_chave_privada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac_certificado',
            name='issuer',
            field=picklefield.fields.PickledObjectField(default=b'\x80\x03cblog.utils\nAlemao\nq\x00)\x81q\x01.', editable=False),
        ),
    ]
