# Generated by Django 3.0.4 on 2020-03-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_ac_certificado_issuer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ac_certificado',
            name='issuer',
        ),
    ]
