# Generated by Django 3.0.4 on 2020-03-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contador'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificados_emitidos',
            name='serial',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
