# Generated by Django 3.0.4 on 2020-03-14 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200313_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificados_emitidos',
            name='issuer',
        ),
    ]
