# Generated by Django 3.0.4 on 2020-03-14 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_certificados_emitidos_issuer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificados_emitidos',
            name='serial',
        ),
    ]
