# Generated by Django 3.0.4 on 2020-03-14 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_certificados_emitidos_serial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificados_emitidos',
        ),
    ]
