# Generated by Django 3.0.4 on 2020-03-14 14:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_certificados_emitidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificados_emitidos',
            name='issuer',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
