# Generated by Django 3.0.4 on 2020-03-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_certificados_emitidos_issuer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificados_emitidos',
            name='certificado',
            field=models.TextField(),
        ),
    ]
