# Generated by Django 3.0.4 on 2020-03-14 23:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200314_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificados_emitidos',
            name='subject',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
