# Generated by Django 3.0.4 on 2020-03-15 14:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_certificados_emitidos_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac_certificado',
            name='issuer',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='ac_certificado',
            name='serial',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ac_certificado',
            name='subject',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='ac_certificado',
            name='cert_autoassinado',
            field=models.TextField(),
        ),
    ]
